=== hosseinmd/swagger-typescript/schema/v6.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "url": {
      "description": "Path of openApi, could be file or internet address",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "branch": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": ["branch", "url"]
          }
        }
      ]
    },
    "dir": {
      "type": "string",
      "filePathExists": true,
      "description": "Destination folder which generated file will be there. Start from root of project"
    },
    "keepJson": {
      "type": "boolean",
      "default": false,
      "description": "Useful when you want to keep a json version in your local"
    },
    "reactHooks": {
      "type": "boolean",
      "default": false,
      "description": "Generate react hooks for every api"
    },
    "useQuery": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "If an api is post but you want to generate it as get Api add name of it hook to this array"
    },
    "useInfiniteQuery": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "To infinity load functionality for your api hook add hook name to this array"
    },
    "language": {
      "type": "string",
      "enum": ["javascript", "typescript", "kotlin"],
      "description": "Target language"
    },
    "prettierPath": {
      "type": "string",
      "description": "Path of prettier config file"
    },
    "methodName": {
      "type": "string",
      "description": "For customizing method name"
    },
    "prefix": {
      "type": "string",
      "description": "Prefix of Apis which you want to remove for example: `/api`"
    },
    "ignore": {
      "type": "object",
      "properties": {
        "headerParams": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "For ignore property from all of api to not generating"
    },
    "generateEnumAsType": {
      "type": "boolean"
    },
    "kotlinPackage": {
      "description": "Package name of distance",
      "type": "string"
    }
  },
  "required": ["url", "dir"]
}

=== hosseinmd/swagger-typescript/__tests__/e2e/swagger.config-1.json
{
  "$schema": "../../schema/v6.json",
  "url": [
    {
      "branch": "master",
      "url": "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json"
    },
    {
      "branch": "develop",
      "url": "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json"
    }
  ],
  "dir": "./__tests__/e2e/swagger-output-0",
  "language": "typescript",
  "keepJson": true,
  "reactHooks": true,
  "useInfiniteQuery": ["useGetRealmsRealm"],
  "ignore": {
    "headerParams": ["terminalId"]
  }
}

=== hosseinmd/swagger-typescript/__tests__/e2e/swagger.config.json
{
  "$schema": "../../schema/v6.json",
  "url": "https://bitfinity.postman.co/workspace/Bitfinity~0878e325-dcc5-4adf-b37e-ac68386085f4/collection/4699480-5297d2ce-9573-4bca-a65b-5451c9809055?action=share&creator=4699480",
  "dir": "./__tests__/e2e/swagger-output-1",
  "language": "kotlin",
  "kotlinPackage": "com.wms.wms.data.api",
  "ignore": {
    "headerParams": ["Accept", "Content-Encoding", "Content-Type"]
  }
}

=== hosseinmd/swagger-typescript/__tests__/e2e/local-openapi-2.config.json
{
  "$schema": "../../schema/v6.json",
  "url": "./__tests__/e2e/local-openapi-2.json",
  "dir": "./__tests__/e2e/outputs/local-openapi-2",
  "reactHooks": true,
  "generateEnumAsType": true,
  "useInfiniteQuery": [
    "useGetSuppliersSuppliers",
    "useGetWarehouseWarehouses",
    "useGetFinanceAccounts"
  ]
}
